<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../../'))" />

  <PropertyGroup>
    <TargetFrameworks>$(LibraryTargetFrameworks)</TargetFrameworks>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition="$(DefineConstants.Contains(NET6_0_OR_GREATER))">
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <PropertyGroup Condition="$(DefineConstants.Contains(NET8_0_OR_GREATER))">
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup Condition="$(DefineConstants.Contains(TRAKT_NETSTANDARD_TARGET))">
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

</Project>
