<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <!-- Libraries Dependencies -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <PackageVersion Include="Nerdbank.GitVersioning" Version="3.7.115" />
    <PackageVersion Include="System.Text.Json" Version="9.0.1" />
  </ItemGroup>

  <!-- HttpClientFactory Dependencies -->
  <ItemGroup Condition="('$(TargetFramework)' == 'net5.0')">
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="5.0.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="5.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup Condition="('$(TargetFramework)' == 'net6.0')">
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="6.0.2" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="6.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup Condition="('$(TargetFramework)' == 'net7.0')">
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup Condition="('$(TargetFramework)' == 'net8.0')">
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup Condition="('$(TargetFramework)' == 'net9.0') OR $(DefineConstants.Contains(TRAKT_NETSTANDARD_TARGET))">
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="9.0.1" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="9.0.1" />
  </ItemGroup>

  <!-- Tests Dependencies -->
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="coverlet.msbuild" Version="6.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="RichardSzalay.MockHttp" Version="7.0.0" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="System.Net.Http" Version="4.3.4" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.0.1" />
  </ItemGroup>

  <!-- Tools Source Generators Dependencies -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" />
  </ItemGroup>

  <!-- Tests Source Generators Dependencies -->
  <ItemGroup>
    <PackageVersion Include="Basic.Reference.Assemblies" Version="1.8.0" />
    <PackageVersion Include="Verify.DiffPlex" Version="3.1.2" />
    <PackageVersion Include="Verify.SourceGenerators" Version="2.4.3" />
    <PackageVersion Include="Verify.Xunit" Version="28.8.0" />
  </ItemGroup>

</Project>
