<Project>

  <!-- Custom constants and variables. -->
  <PropertyGroup>
    <LibraryCopyright>© 2016 - $([System.DateTime]::Now.ToString("yyyy")) by Henrik Fröhling and Contributors</LibraryCopyright>

    <!-- NET (Framework | Standard) Targets -->
    <LibraryNETFrameworkTargets>net472;net481</LibraryNETFrameworkTargets>
    <LibraryNETStandardTargets>netstandard2.0;netstandard2.1</LibraryNETStandardTargets>
    <LibraryCommonNETTargets>net6.0;net7.0;net8.0;net9.0</LibraryCommonNETTargets>
    <LibraryCommonNETPreviewTargets></LibraryCommonNETPreviewTargets>

    <LibraryTargetFrameworks>$(LibraryNETStandardTargets);net5.0;$(LibraryCommonNETTargets)</LibraryTargetFrameworks>
    <TestTargetFrameworks>$(LibraryNETFrameworkTargets);$(LibraryCommonNETTargets)</TestTargetFrameworks>

    <!-- These tests use Verify packages which only support these .NET versions >= 6. -->
    <SourceGenerationTestTargetFrameworks>net6.0;net7.0;net8.0</SourceGenerationTestTargetFrameworks>

    <IsTestProject>$(MSBuildProjectName.EndsWith('Tests'))</IsTestProject>
    <IsTestUtilityProject>$(MSBuildProjectName.EndsWith('Tests.Utility'))</IsTestUtilityProject>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);1701;1702;1705;1591</NoWarn>
    <Copyright>$(LibraryCopyright)</Copyright>

    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TraktNET</RootNamespace>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <WarningLevel>7</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
  </PropertyGroup>

</Project>
