<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <!-- Libraries Dependencies -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <PackageVersion Include="Nerdbank.GitVersioning" Version="3.6.141" />
    <PackageVersion Include="System.Text.Json" Version="8.0.4" />
  </ItemGroup>

  <!-- Tests Dependencies -->
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="6.0.2" />
    <PackageVersion Include="coverlet.msbuild" Version="6.0.2" />
    <PackageVersion Include="FluentAssertions" Version="6.12.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.11.0" />
    <PackageVersion Include="RichardSzalay.MockHttp" Version="7.0.0" />
    <PackageVersion Include="System.Net.Http" Version="4.3.4" />
    <PackageVersion Include="xunit" Version="2.9.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <!-- Tools Source Generators Dependencies -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" />
  </ItemGroup>

  <!-- Tests Source Generators Dependencies -->
  <ItemGroup>
    <PackageVersion Include="Basic.Reference.Assemblies" Version="1.7.8" />
    <PackageVersion Include="Verify.DiffPlex" Version="3.1.0" />
    <PackageVersion Include="Verify.SourceGenerators" Version="2.3.0" />
    <PackageVersion Include="Verify.Xunit" Version="26.2.0" />
  </ItemGroup>

</Project>
