namespace TraktNET.SourceGenerators
{
    internal static class Constants
    {
        internal const string Header = @"//-----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Trakt.NET source generator.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------------

#nullable enable
";

        internal const string ExcludeCodeCoverage = @"#if NET5_0_OR_GREATER
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = ""Generated by the Trakt.NET source generator."")]
#else
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif";

        internal const string TraktEnumAttribute = Header + @"
namespace TraktNET.SourceGenerators
{
    /// <summary>Provides extension methods and a Json converter for an enum.</summary>
" + ExcludeCodeCoverage + @"
    [global::System.AttributeUsage(global::System.AttributeTargets.Enum)]
    public sealed class TraktEnumAttribute : global::System.Attribute
    {
    }
}
";

        internal const string FullTraktEnumAttributeName = "TraktNET.SourceGenerators.TraktEnumAttribute";

        internal const string GeneratedTraktEnumAttributeFilename = "TraktEnumAttribute.g.cs";

        internal const string GeneratedTraktEnumFileExtension = "EnumExtensions.g.cs";

        internal const string TraktEnumAttributeName = "TraktEnumAttribute";

        internal static class TrackingNames
        {
            internal const string InitialEnumExtraction = "InitialEnumExtraction";

            internal const string NullFilteredEnums = "NullFilteredEnums";
        }
    }
}
