name: "Deployment"

on:
  workflow_dispatch:
  push:
    tags: [v*]

env:
  BUILD_TYPE: Release
  SOLUTION_NAME: 'Source\Trakt.NET.sln'
  PROJECT_NAME: 'Source\Lib\Trakt.NET\Trakt.NET.csproj'
  BUILD_DIRECTORY: 'Build\Lib\Release\netstandard2.0'
  VERSION_NUMBER: ''

jobs:
  deployment:
    name: "Deployment"
    runs-on: windows-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_NAME }}
      - name: Build solution
        run: dotnet build ${{ env.SOLUTION_NAME }} --configuration ${{ env.BUILD_TYPE }} --no-restore /m /p:BuildInParallel=true
      - name: Get version number
        shell: pwsh
        run: |
          [xml]$csprojcontents = Get-Content -Path ${{ env.PROJECT_NAME }}
          $versionNumber = "$($csprojcontents.Project.PropertyGroup.VersionPrefix)".Trim()
          Write-Host "Found version:" $versionNumber
          echo "VERSION_NUMBER=$versionNumber" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
      - name: Nuget pack
        run: dotnet pack ${{ env.PROJECT_NAME }} --configuration ${{ env.BUILD_TYPE }} --verbosity detailed --output ${{ env.BUILD_DIRECTORY }} -p:PackageID="Trakt.NET.${{ env.VERSION_NUMBER }}" --no-build --no-restore
      - name: Rename artifacts
        shell: pwsh
        run: Get-ChildItem -Path ${{ env.BUILD_DIRECTORY }} | Where-Object {$_.Extension -match '.dll|.pdb|.xml|.nupkg'} | Rename-Item -NewName {'Trakt.NET.' + '${{ env.VERSION_NUMBER }}' + $_.Extension}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Trakt.NET.${{ env.VERSION_NUMBER }}-${{github.sha}}
          path: |
            ${{ env.BUILD_DIRECTORY }}/Trakt.NET*.dll
            ${{ env.BUILD_DIRECTORY }}/Trakt.NET*.pdb
            ${{ env.BUILD_DIRECTORY }}/Trakt.NET*.xml
            ${{ env.BUILD_DIRECTORY }}/Trakt.NET*.nupkg
      - name: Add GitHub packages source
        run: dotnet nuget add source --username henrikfroehling --password ${{ secrets.PAT_GITHUB }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/henrikfroehling/index.json"
      - name: Push GitHub package
        run: dotnet nuget push "${{ env.BUILD_DIRECTORY }}\Trakt.NET*.nupkg" --api-key ${{ secrets.PAT_GITHUB }} --source "github"
      - name: Push NuGet package
        run: dotnet nuget push "${{ env.BUILD_DIRECTORY }}\Trakt.NET*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json"
