name: Trakt.NET-CI-Developer-Preview

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest
    env:
      Solution_Name: 'Source/Trakt.NET.sln'
      Test_Projects: 'Source/Tests'

    steps:
    - name: Get Sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Restore packages
      run: dotnet restore $env:Solution_Name
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Build solution
      run: dotnet build $env:Solution_Name --configuration $env:Configuration --no-restore /m /p:BuildInParallel=true
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Run tests
      run: dotnet test $env:Test_Projects --configuration $env:Configuration --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[xunit*]*"
      env:
        Configuration: ${{ matrix.configuration }}
